user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

tickets:
    resource: "@TicketsBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"